### PR TITLE
add intergration

### LINKED ISSUE #20: Intergrataion
run all methods in 1 main

### PR DESCRIPTION
**Pull request by yuqi88**
close #20

### CODE REVIEW

**Review by aliL2000 — APPROVED** [review]
Changes look good to me, this is testing the correctness of the code.

**Comment by aliL2000** [comment]
Closes #20

**Review by Brenden-Trieu — COMMENTED** [review]
Code works

**Comment by yuqi88** [comment]
It is linked to the issue 20

**Review by Brenden-Trieu — APPROVED** [review]

**Comment by yuqi88** [comment]
image

**Pull request merged**
